version: '3.7'
services:
  caster:
    build: 
      dockerfile: Dockerfile
      args:
        #Global args
        OGG_STREAM_ENDPOINT: /stream
        MPEG_STREAM_ENDPOINT: /backup_stream

        #API/Services Args
        PORT: 4000
        ICECAST_PASSWORD: password #As long as you dont forward port 8000 this does not need to be secure as its not exposed
        
        #Frontend Build Args
        WEB_PAGE_TITLE: Phonk Live - 24/7 Phonk Radio
        WEB_HEADER: Phonk.Live
        WEB_SUBTITLE: 24/7 Phonk Radio
        WEB_BACKGROUND_COLOUR: "#1D1F2B"
        WEB_ACCENT_COLOUR: "#32CD32"
        SOCKET_IO_PROTOCOL: wss # WSS,WS,HTTPS,HTTP
        DOMAIN: phonk.live
        WEB_PROTOCOL: https
                
    container_name: caster
    restart: always
    ports:
      - 4000:4000
    volumes:
      - ./casting/playlist.txt:/etc/ices2/playlist.txt
      - ./casting/songs:/etc/ices2/songs